"use client";

import { useState } from "react";
import { AdminProductForm } from "@/components/AdminProductForm";
import { money, dateTime } from "@/lib/format";
import type { Order, Product, Profile, OrderItem, OrderStatus } from "@/types/database";

type AdminOrder = Order & { profile: Pick<Profile, "first_name" | "last_name" | "email"> | null; items: Array<OrderItem & { product: Pick<Product, "name"> | null }> };

export function AdminDashboard({ initialProducts, initialProfiles, initialOrders }: { initialProducts: Product[]; initialProfiles: Profile[]; initialOrders: AdminOrder[] }) {
  const [products, setProducts] = useState(initialProducts);
  const [profiles, setProfiles] = useState(initialProfiles);
  const [orders, setOrders] = useState(initialOrders);
  const [editing, setEditing] = useState<Product | undefined>();
  const [message, setMessage] = useState("");

  async function refreshProducts() { const response = await fetch("/api/admin/products"); const data = await response.json(); if (response.ok) setProducts(data.products); }
  async function deleteProduct(id: number) { if (!window.confirm("Delete this product?")) return; const response = await fetch(`/api/admin/products/${id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Unable to delete product."); await refreshProducts(); }
  async function updateStatus(id: string, status: OrderStatus) { const response = await fetch(`/api/admin/orders/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Unable to update order."); setOrders((current) => current.map((order) => order.id === id ? { ...order, status } : order)); }
  async function deleteUser(id: string) { if (!window.confirm("Delete this registered application profile?")) return; const response = await fetch(`/api/admin/users/${id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Unable to delete user."); setProfiles((current) => current.filter((profile) => profile.id !== id)); }
  async function updateUser(id: string, field: "first_name" | "last_name" | "phone" | "address", value: string) { const response = await fetch(`/api/admin/users/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ [field]: value }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Unable to update user."); setProfiles((current) => current.map((profile) => profile.id === id ? { ...profile, [field]: value } : profile)); }

  return <div className="space-y-8">{message && <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</div>}
    <section><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-semibold">Products</h2>{!editing && <button onClick={() => setEditing({ id: 0, name: "", description: "", price: 0, image_url: "", created_at: "", updated_at: "" })} className="rounded-lg bg-gray-900 px-4 py-2 text-sm text-white">Add product</button>}</div>{editing && <div className="mb-4"><AdminProductForm product={editing.id ? editing : undefined} onDone={async () => { setEditing(undefined); await refreshProducts(); }} /></div>}<div className="grid gap-4 md:grid-cols-2">{products.map((product) => <div key={product.id} className="rounded-xl border bg-white p-4"><div className="flex gap-3"><img src={product.image_url} alt={product.name} className="h-16 w-16 rounded object-cover" /><div className="min-w-0 flex-1"><h3 className="font-semibold">{product.name}</h3><p className="text-sm text-gray-500">{money(product.price)}</p></div></div><p className="mt-2 line-clamp-2 text-sm text-gray-600">{product.description}</p><div className="mt-3 flex gap-2"><button onClick={() => setEditing(product)} className="rounded-lg border px-3 py-2 text-sm">Edit</button><button onClick={() => deleteProduct(product.id)} className="rounded-lg border border-red-200 px-3 py-2 text-sm text-red-600">Delete</button></div></div>)}</div></section>
    <section><h2 className="mb-4 text-xl font-semibold">Users</h2><div className="space-y-3">{profiles.map((profile) => <div key={profile.id} className="rounded-xl border bg-white p-4"><div className="grid gap-3 md:grid-cols-2"><p><span className="font-medium">Email:</span> {profile.email}</p><p><span className="font-medium">Role:</span> {profile.role}</p><label>First name<input value={profile.first_name} onChange={(event) => void updateUser(profile.id, "first_name", event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label>Last name<input value={profile.last_name} onChange={(event) => void updateUser(profile.id, "last_name", event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label>Phone<input value={profile.phone} onChange={(event) => void updateUser(profile.id, "phone", event.target.value)} className="mt-1 w-full rounded border p-2" /></label><label>Address<input value={profile.address} onChange={(event) => void updateUser(profile.id, "address", event.target.value)} className="mt-1 w-full rounded border p-2" /></label></div><button onClick={() => deleteUser(profile.id)} className="mt-3 rounded-lg border border-red-200 px-3 py-2 text-sm text-red-600">Delete profile</button></div>)}</div></section>
    <section><h2 className="mb-4 text-xl font-semibold">Orders</h2><div className="space-y-4">{orders.map((order) => <div key={order.id} className="rounded-xl border bg-white p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold">{order.profile?.first_name} {order.profile?.last_name}</p><p className="text-sm text-gray-500">{order.profile?.email} · {dateTime(order.created_at)}</p></div><div className="flex items-center gap-3"><span className="font-semibold">{money(order.total_amount)}</span><select value={order.status} onChange={(event) => void updateStatus(order.id, event.target.value as OrderStatus)} className="rounded-lg border px-3 py-2">{["PENDING", "CONFIRMED", "SHIPPED", "DELIVERED", "CANCELLED"].map((status) => <option key={status}>{status}</option>)}</select></div></div><p className="mt-2 text-sm text-gray-600">{order.address}</p><div className="mt-3 space-y-2">{order.items.map((item) => <div key={item.id} className="flex justify-between text-sm"><span>{item.product?.name ?? `Product #${item.product_id}`} × {item.quantity}</span><span>{money(Number(item.unit_price) * item.quantity)}</span></div>)}</div></div>)}</div></section>
  </div>;
}
